#!/usr/bin/env node
/* ============================================================
   Build script — multi-page static site
   - Concatenates src/js/core/*.js + src/js/content/*.js (numeric
     order) into a single dist/script.js
   - Copies src/style.css -> dist/style.css
   - Requires dist/script.js to read the content DB + DS cards
   - Generates one static HTML page per content page from
     src/template.html, each with a page-scoped sidebar
   ============================================================ */

'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const BANNER = '/* ============================================================\n' +
    '   DSA Knowledge Base - script.js (generated by build.js)\n' +
    '   Do NOT edit this file directly - edit src/js/** modules.\n' +
    '   ============================================================ */\n';

function listModules(dir) {
    return fs.readdirSync(dir)
        .filter((f) => /^\d+[\w-]+\.js$/.test(f))
        .sort();
}

/* ---------- 1. assemble script.js ---------- */
let js = BANNER + "'use strict';\n\n";
listModules(path.join(SRC, 'js/core')).forEach((f) => {
    js += '\n/* -------- module: core/' + f + ' -------- */\n\n' + fs.readFileSync(path.join(SRC, 'js/core', f), 'utf8').trimEnd() + '\n';
});
listModules(path.join(SRC, 'js/content')).forEach((f) => {
    js += '\n/* -------- module: content/' + f + ' -------- */\n\n' + fs.readFileSync(path.join(SRC, 'js/content', f), 'utf8').trimEnd() + '\n';
});
js += '\n';

/* regression guards */
if (!/function \$\$/.test(js)) { console.error('BUILD FAILED: function $$ missing ($$ mangling regression)'); process.exit(1); }
if ((js.match(/function \$\(/g) || []).length !== 1) { console.error('BUILD FAILED: expected exactly one function $('); process.exit(1); }
if (!js.includes('var DB = {};')) { console.error('BUILD FAILED: var DB container missing'); process.exit(1); }

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, 'script.js'), js);

/* ---------- 2. copy static assets ---------- */
fs.copyFileSync(path.join(SRC, 'style.css'), path.join(DIST, 'style.css'));

/* ---------- 3. load the content DB from the built bundle ---------- */
const app = require(path.join(DIST, 'script.js'));
const { DB, DS_CARDS, pageFile } = app;

/* ---------- 4. sidebar generator ---------- */
function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const HOME_ICON = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>';
const CHEVRON_ICON = '<svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"></polyline></svg>';
const ARRAY_ICON = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="2" width="8" height="8" rx="1.5"/><rect x="14" y="2" width="8" height="8" rx="1.5"/><rect x="2" y="14" width="8" height="8" rx="1.5"/><rect x="14" y="14" width="8" height="8" rx="1.5"/></svg>';

const ARRAY_NAV = {
    'research/index': 'Introduction',
    'research/array': 'Array Notes',
    'topics/traversal': 'Traversal',
    'topics/prefix-sum': 'Prefix Sum',
    'topics/difference-array': 'Difference Array',
    'topics/sliding-window': 'Sliding Window',
    'topics/two-pointers': 'Two Pointers',
    'topics/kadane': 'Kadane Algorithm',
    'topics/sorting': 'Sorting',
    'topics/binary-search': 'Binary Search',
    'topics/hashing': 'Hashing',
    'topics/matrix': 'Matrix / 2D Array',
    'topics/merge-intervals': 'Merge Intervals',
    'topics/dutch-national-flag': 'Dutch National Flag',
    'topics/binary-search-answer': 'Binary Search on Answer',
    'topics/complexity': 'Complexity Analysis',
    'interview/easy': 'Easy',
    'interview/medium': 'Medium',
    'interview/hard': 'Hard',
    'interview/company': 'Company Wise',
    'interview/theory': 'Theory Questions',
    'leetcode/easy': 'Easy',
    'leetcode/medium': 'Medium',
    'leetcode/hard': 'Hard',
    'leetcode/topic-wise': 'Topic Wise',
    'codeforces/div3': 'Div 3',
    'codeforces/div2': 'Div 2',
    'codeforces/patterns': 'Patterns',
    'snippets': 'Code Snippets',
    'patterns/overview': 'Patterns'
};

const ARRAY_SECTIONS = [
    { title: 'Research', paths: ['research/index', 'research/array'] },
    { title: 'DSA & DAA Topics', paths: [
        'topics/traversal', 'topics/prefix-sum', 'topics/difference-array',
        'topics/sliding-window', 'topics/two-pointers', 'topics/kadane',
        'topics/sorting', 'topics/binary-search', 'topics/hashing',
        'topics/matrix', 'topics/merge-intervals', 'topics/dutch-national-flag',
        'topics/binary-search-answer', 'topics/complexity'
    ] },
    { title: 'Interview Questions', paths: [
        'interview/easy', 'interview/medium', 'interview/hard',
        'interview/company', 'interview/theory'
    ] },
    { title: 'LeetCode', paths: ['leetcode/easy', 'leetcode/medium', 'leetcode/hard', 'leetcode/topic-wise'] },
    { title: 'Codeforces', paths: ['codeforces/div3', 'codeforces/div2', 'codeforces/patterns'] },
    { title: 'Code Snippets', paths: ['snippets'] },
    { title: 'Patterns', paths: ['patterns/overview'] }
];

const LEARN_PAGES = {
    'learn/getting-started': 'Getting Started',
    'learn/glossary': 'Glossary',
    'learn/references': 'References'
};

function isArrayPath(p) {
    return p.indexOf('research/') === 0 || p.indexOf('topics/') === 0 ||
        p.indexOf('interview/') === 0 || p.indexOf('leetcode/') === 0 ||
        p.indexOf('codeforces/') === 0 || p === 'snippets' ||
        p.indexOf('patterns/') === 0;
}

function arrayNav(currentPath) {
    const open = isArrayPath(currentPath);
    let html = '<div class="nav-item nav-parent' + (open ? ' expanded' : '') + '" data-path="array">' +
        CHEVRON_ICON + ARRAY_ICON + '<span>Array</span></div>';
    html += '<div class="nav-children' + (open ? ' open' : '') + '" id="array-children">';
    ARRAY_SECTIONS.forEach((sec) => {
        html += '<div class="nav-section-title nav-group-title">' + esc(sec.title) + '</div>';
        sec.paths.forEach((p) => {
            html += '<a href="' + pageFile(p) + '" class="nav-item' + (currentPath === p ? ' active' : '') + '" data-path="' + esc(p) + '">' + esc(ARRAY_NAV[p] || p) + '</a>';
        });
    });
    html += '</div>';
    return html;
}

function moreDSNav(currentPath) {
    let html = '';
    DS_CARDS.forEach((c) => {
        if (c.status === 'active') return;
        const icon = c.icon.replace(/width="28"/, 'width="20"');
        html += '<a href="' + pageFile(c.path) + '" class="nav-item' + (currentPath === c.path ? ' active' : '') + '" data-path="' + esc(c.path) + '">' +
            icon + '<span>' + esc(c.title) + '</span><span class="nav-badge-soon">Soon</span></a>';
    });
    return html;
}

function buildSidebar(currentPath) {
    let html = '';
    html += '<div class="nav-section"><div class="nav-section-title">Home</div>';
    html += '<a href="index.html" class="nav-item' + (currentPath === 'home' ? ' active' : '') + '" data-path="home">' + HOME_ICON + '<span>Dashboard</span></a>';
    html += '</div>';
    html += '<div class="nav-section"><div class="nav-section-title">Data Structures</div>' + arrayNav(currentPath) + '</div>';
    html += '<div class="nav-section"><div class="nav-section-title">More Data Structures</div>' + moreDSNav(currentPath) + '</div>';
    html += '<div class="nav-section"><div class="nav-section-title">Learn</div>';
    Object.keys(LEARN_PAGES).forEach((p) => {
        html += '<a href="' + pageFile(p) + '" class="nav-item' + (currentPath === p ? ' active' : '') + '" data-path="' + esc(p) + '">' + esc(LEARN_PAGES[p]) + '</a>';
    });
    html += '</div>';
    return html;
}

/* ---------- 5. page title ---------- */
function pageTitle(currentPath) {
    if (currentPath === 'home') return 'DSA Knowledge Base — Dashboard';
    if (currentPath.indexOf('coming-soon/') === 0) {
        const c = DS_CARDS.find((x) => x.path === currentPath);
        return (c ? c.title : 'Coming Soon') + ' — Coming Soon — DSA Knowledge Base';
    }
    const d = DB[currentPath];
    return (d ? d.title : currentPath) + ' — DSA Knowledge Base';
}

/* ---------- 6. generate pages ---------- */
const template = fs.readFileSync(path.join(SRC, 'template.html'), 'utf8');

const pages = [];
pages.push({ file: 'index.html', path: 'home' });
Object.keys(DB).forEach((p) => {
    if (p === 'home') return;
    pages.push({ file: pageFile(p), path: p });
});
DS_CARDS.forEach((c) => {
    if (c.path.indexOf('coming-soon/') === 0) pages.push({ file: pageFile(c.path), path: c.path });
});

const seen = {};
const unique = [];
pages.forEach((pg) => {
    if (seen[pg.file]) return;
    seen[pg.file] = true;
    unique.push(pg);
});
unique.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0));

unique.forEach((pg) => {
    const html = template
        .replace(/\{\{TITLE\}\}/g, pageTitle(pg.path))
        .replace(/\{\{BODY_PATH\}\}/g, pg.path)
        .replace(/\{\{SIDEBAR\}\}/g, buildSidebar(pg.path));
    fs.writeFileSync(path.join(DIST, pg.file), html, 'utf8');
});

console.log('Built dist/script.js (' + Math.round(js.length / 1024) + ' KB)');
console.log('Copied dist/style.css');
console.log('Generated ' + unique.length + ' HTML pages');

/* ---------- 7. standalone single-file build ----------
   Inlines style.css + script.js into one self-contained HTML so the
   app runs from any single-file context: http://, file:// and Android
   content:// (which cannot load sibling assets). */
(function buildStandalone() {
    const css = fs.readFileSync(path.join(DIST, 'style.css'), 'utf8');
    const appJs = fs.readFileSync(path.join(DIST, 'script.js'), 'utf8');
    const standalone = template
        .replace(/\{\{TITLE\}\}/g, 'DSA Knowledge Base — Offline Standalone')
        .replace(/\{\{BODY_PATH\}\}/g, 'home')
        .replace(/\{\{SIDEBAR\}\}/g, buildSidebar('home'))
        .replace('<link rel="stylesheet" href="style.css">', function () { return '<style>\n' + css + '\n</style>'; })
        .replace('<script src="script.js"></script>', function () { return '<script>\n' + appJs + '\n</script>'; });
    fs.writeFileSync(path.join(DIST, 'index.standalone.html'), standalone);
    /* regression guard: the inlined script must be byte-identical to
       dist/script.js — a mangled $$ / $& / $1 would silently break the app */
    const back = standalone.match(/<script>([\s\S]*?)<\/script>/);
    if (!back || back[1].replace(/^\n/, '').replace(/\n$/, '') !== appJs) {
        console.error('BUILD FAILED: standalone script differs from script.js ($$ mangling regression)');
        process.exit(1);
    }
    console.log('Built dist/index.standalone.html (' + Math.round(standalone.length / 1024) + ' KB)');
})();
