/* ============================================================
   DSA Knowledge Base - script.js (module: content:19-learn)
   Content Database + App Logic | Vanilla JS | No dependencies
   ============================================================ */

/* Pages: learn/getting-started, learn/glossary, learn/references */

DB["learn/getting-started"] = {
    title: 'Getting Started',
    crumbs: ['Home', 'Learn', 'Getting Started'],
    tags: ['learn', 'getting-started', 'guide', 'roadmap', 'study'],
    content: [
        '# Getting Started',
        '',
        'A quick tour of the site and a concrete study plan. If you are new to DSA, start here and follow the path bottom-up. If you are revising, jump straight to the [Patterns cheat sheet](patterns/overview) and drill the [snippets](snippets).',
        '',
        '## How This Site Is Organized',
        '',
        'The sidebar mirrors a real study syllabus:',
        '',
        '| Section | What it gives you |',
        '|---|---|',
        '| **Research** | How arrays actually work in memory (cache lines, resizing, complexity). |',
        '| **DSA & DAA Topics** | 14 array topics, each with history, intuition, trace, proof, and pitfalls. |',
        '| **Interview Questions** | 16 cards: easy, medium, hard — each with a 5-language solution. |',
        '| **LeetCode / Codeforces** | Pattern-first practice lists and contest tricks. |',
        '| **Code Snippets** | 11 programs in all 5 languages, explained line by line. |',
        '| **Patterns** | The detector-phrase cheat sheet that names the algorithm before you code. |',
        '',
        '## Reading the Code Blocks',
        '',
        'Every explained group is a tabbed widget: **C · C++ · Java · Python · Dart**. Pick your preferred language once and every group will default to it:',
        '',
        '1. On the home page, choose your language in the modal (or the **Preferred language** bar anytime).',
        '2. Inside any group, click a tab or use the `<select>` in a block header to switch.',
        '3. **View code** on a problem card scrolls to and highlights that problem\'s solution.',
        '4. **Copy** grabs the exact source; **Expand/Collapse** frees screen space.',
        '',
        'Each explained line carries a reference (language docs, papers, or the cppreference/Oracle/Python/Dart pages) so you can read the *why* behind every line.',
        '',
        '> [!info] The `~~~io` boxes',
        '> Every program group is paired with a **Sample Input / Sample Output (expected)** box. Run the code mentally against it to check your understanding of the trace.',
        '',
        '## A 4-Week Study Path',
        '',
        'Do each block in order. A block is complete when you can re-derive the code with your eyes closed.',
        '',
        '**Week 1 — Foundations**',
        '',
        '1. [Array Research](research/array) — memory layout, cache, complexity.',
        '2. [Traversal](topics/traversal) — forward, reverse, strides.',
        '3. [Complexity Analysis](topics/complexity) — Big-O, space, proofs.',
        '4. [Prefix Sum](topics/prefix-sum) + [Difference Array](topics/difference-array).',
        '',
        '**Week 2 — The Workhorse Patterns**',
        '',
        '1. [Two Pointers](topics/two-pointers)',
        '2. [Sliding Window](topics/sliding-window)',
        '3. [Kadane](topics/kadane)',
        '4. [Sorting](topics/bubble-sort)',
        '',
        '**Week 3 — Search & Grouping**',
        '',
        '1. [Binary Search](topics/binary-search)',
        '2. [Binary Search on Answer](topics/binary-search-answer)',
        '3. [Hashing](topics/hashing)',
        '4. [Merge Intervals](topics/merge-intervals)',
        '',
        '**Week 4 — Consolidation**',
        '',
        '1. [Matrix](topics/matrix) + [Dutch National Flag](topics/dutch-national-flag).',
        '2. Re-solve the [easy interview set](interview/easy), then the [medium](interview/medium).',
        '3. Drill the [snippets](snippets) page — one group per sitting.',
        '4. End each week by re-deriving the [Patterns cheat sheet](patterns/overview) from memory.',
        '',
        '## The Daily Workout',
        '',
        '> [!success] Study loop',
        '> 1. Read a topic\'s intuition + trace. 2. Close the page and write the algorithm on paper. 3. Compare with the 5-language program. 4. State the complexity and prove it. 5. Solve one tagged problem in the LeetCode/Interview pages using that pattern.',
        '',
        '## Quick Checks',
        '',
        '- Use **search** (press `/`) to jump anywhere in seconds.',
        '- **Ctrl+B** (or the bookmark icon) saves a page for later.',
        '- The **theme toggle** switches light/dark and remembers your choice.',
        '- Everything works fully offline — no server, no build tool, no network.'
    ].join('\n')
};

DB["learn/glossary"] = {
    title: 'Glossary',
    crumbs: ['Home', 'Learn', 'Glossary'],
    tags: ['learn', 'glossary', 'terms', 'definitions', 'reference'],
    content: [
        '# Glossary',
        '',
        'The vocabulary used across the site. Master these terms and problem statements stop feeling foreign.',
        '',
        '| Term | Meaning |',
        '|---|---|',
        '| **Algorithm** | A finite, unambiguous sequence of steps that maps an input to an output. |',
        '| **Amortized cost** | Average cost per operation over a sequence, even when single operations are expensive (e.g. dynamic-array doubling is O(1) amortized). |',
        '| **Array** | Contiguous block of memory addressed by consecutive integers; `arr[i]` is at `base + i * sizeof(element)`. |',
        '| **Asymptotic analysis** | Describing growth of time/space as input size `n → ∞`, ignoring constant factors. |',
        '| **Big-O, `O(f(n))`** | An upper bound: the resource grows no faster than `f(n)` for large `n`. Bachmann 1894. |',
        '| **Big-Omega, `Ω(f(n))`** | A lower bound: the resource grows at least as fast as `f(n)` — used to prove optimality. |',
        '| **Big-Theta, `Θ(f(n))`** | A tight bound: both `O` and `Ω` hold. |',
        '| **Cache locality** | Consecutive data sharing a cache line, making sequential scans fast. |',
        '| **Contiguous** | Elements stored next to each other in memory with no gaps. |',
        '| **Data structure** | A way of organizing data plus the operations supported on it (array, hash table, heap, …). |',
        '| **Difference array** | `diff[i] = a[i] - a[i-1]`; enables O(1) range updates, O(n) materialization. |',
        '| **Hash table** | Maps keys to values via a hash function; O(1) average insert/lookup. |',
        '| **In-place** | An algorithm using O(1) extra space besides the input. |',
        '| **Invariant** | A property that holds before and after every loop iteration — the heart of a correctness proof. |',
        '| **Kadane\'s algorithm** | O(n) single-pass maximum subarray sum via `dp[i] = max(a[i], dp[i-1] + a[i])`. |',
        '| **Monotone** | Non-decreasing or non-increasing; a predicate that flips once makes binary search valid. |',
        '| **Pattern** | A reusable algorithmic idea (sliding window, two pointers, …) matched by problem phrasing. |',
        '| **Prefix sum** | `pref[i]` = sum of `a[0..i-1]`; answers range sums in O(1) after an O(n) build. |',
        '| **Recurrence** | A relation defining a value in terms of earlier values (e.g. the Kadane recurrence). |',
        '| **Sliding window** | Two indices bounding a contiguous segment that slides; O(n) total work. |',
        '| **Space complexity** | Extra memory used, as a function of input size. |',
        '| **Subarray** | A contiguous slice of an array (positions `i..j`). |',
        '| **Subsequence** | A sequence derived by deleting zero or more elements, *preserving order* but not necessarily contiguous. |',
        '| **Time complexity** | Number of primitive operations, as a function of input size. |',
        '| **Two pointers** | Two indices moving toward or alongside each other to replace a nested loop. |',
        '',
        '> [!info] Subarray vs subsequence',
        '> `[3, -1]` is a subarray of `[1, 3, -1, 2]` but `[1, -1]` is only a subsequence. Kadane finds the maximum-sum **subarray**; LIS works on **subsequences** — the constraint change rewrites the algorithm.',
        '',
        '## Reading the Big-O Table',
        '',
        'When you see `O(f(n))` in the site\'s complexity tables, translate it as:',
        '',
        '| `O(f(n))` | Feels like |',
        '|---|---|',
        '| O(1) | one step |',
        '| O(log n) | halving repeatedly |',
        '| O(n) | one scan |',
        '| O(n log n) | sort-and-sweep, divide-and-conquer |',
        '| O(n²) | nested loops |',
        '| O(2ⁿ) | subset enumeration |',
        '',
        '## Quick Self-Test',
        '',
        '1. Why is array access O(1)? → Address arithmetic `base + offset`.',
        '2. What makes a predicate binary-searchable? → Monotonicity. See [Binary Search](topics/binary-search).',
        '3. Subarray or subsequence: `[2, 4]` in `[1, 2, 3, 4]`? → Subarray (indices 1–2).',
        '4. What is the amortized cost of appending to a dynamic array? → O(1).',
        '5. When does a difference array beat a prefix sum? → Many range *updates* first, few *queries* after.'
    ].join('\n')
};

DB["learn/references"] = {
    title: 'References',
    crumbs: ['Home', 'Learn', 'References'],
    tags: ['learn', 'references', 'sources', 'bibliography', 'citations'],
    content: [
        '# References',
        '',
        'Every topic\'s **History & Origin** and every explained line\'s link traces back to a source here. Primary papers first, then the documentation every code line links to.',
        '',
        '> [!info] How citations work on this site',
        '> Prose citations appear as inline links in the History sections. Code-line references use the shorthand `{lang:token}` resolved at render time to the docs below.',
        '',
        '## Papers & Books',
        '',
        '| Source | Used for |',
        '|---|---|',
        '| J. L. Bentley, *Programming Pearls: Algorithm Design Techniques*, CACM 27(9):865, 1984 — [pdf](https://www.cs.rpi.edu/~moorthy/Courses/CSCI2300/p865-bentley.pdf) | Kadane\'s origin story (CMU seminar), binary search variants. |',
        '| U. Grenander, 1977 (Brown University) | Origin of maximum subarray: O(n³) brute force → O(n²) prefix sums. |',
        '| M. I. Shamos | The overnight O(n log n) divide-and-conquer maximum-subarray solution. |',
        '| D. Gries, *The Science of Programming*, 1982 | Dijkstra\'s strategy behind the linear Kadane derivation. |',
        '| R. Bird, 1989 (Bird–Meertens formalism) | Functional derivation of Kadane\'s algorithm. |',
        '| J. Kadane, *A Retrospective on the Maximum Subarray Problem*, Algorithms 2023, 16(11):519 — [MDPI](https://www.mdpi.com/1999-4893/16/11/519) | The taught variant vs the original (all-negative input behaviour). |',
        '| E. W. Dijkstra, *A Discipline of Programming*, 1976 | Dutch National Flag three-way partition. |',
        '| P. Bachmann, *Die Analytische Zahlentheorie*, 1894 | Origin of Big-O notation. |',
        '| J. W. Mauchly, Moore School Lectures, 1946 | Earliest binary-search formulation. |',
        '| W. D. Hillis & G. L. Steele Jr. | Parallel prefix (Hillis–Steele scan). |',
        '| UMD CMSC 351 course notes | Kadane\'s algorithm correctness proof. |',
        '| B. A. Bitner, 1982 | Dutch National Flag analysis. |',
        '',
        '## Online References (coded as `{lang:token}`)',
        '',
        'The explain blocks expand shorthand links into these pages at render time:',
        '',
        '| Language | Docs |',
        '|---|---|',
        '| **C / C++** | [cppreference](https://en.cppreference.com/w/) — headers, containers, algorithms (`stdio`, `vector`, `sort`, `lower_bound`, `cout`, …). |',
        '| **Java** | [Oracle Java Tutorials](https://docs.oracle.com/javase/tutorial/) + [Java 8 API](https://docs.oracle.com/javase/8/docs/api/) (`Scanner`, `HashMap`, `Arrays`, `System.out`, …). |',
        '| **Python** | [Python 3 Docs](https://docs.python.org/3/) — control flow, `list`/`dict`, `itertools.accumulate`, `collections.Counter`. |',
        '| **Dart** | [Dart Language](https://dart.dev/language) + [API](https://api.dart.dev/) — `main`, `List`, `Map`, loops, `dart:io`. |',
        '',
        '## Web Sources Used in Research',
        '',
        '| Source | Used for |',
        '|---|---|',
        '| [GeeksforGeeks](https://www.geeksforgeeks.org/) | Array storage, difference array, reversal rotation, `bits/stdc++.h`. |',
        '| [LeetCode Editorials](https://leetcode.com/problemset/all/) | LC 121, 283, 169, 56 and the pattern-first lists. |',
        '| [Codeforces](https://codeforces.com/) | Div 2/Div 3 patterns, difference-array problems. |',
        '| [The DSA Handbook](https://thedsahandbook.com/) | Prefix sums, binary-search variants, pattern framing. |',
        '| [Wikipedia](https://en.wikipedia.org/wiki/Array_data_structure) | Array data structure history, Kadane, maximum subarray. |',
        '| [NIST DADS](https://xlinux.nist.gov/dads/) | Dutch National Flag, algorithm terms. |',
        '',
        '> [!success] Why references matter',
        '> Every explained line links to a primary or authoritative page so you never take a line on faith. If a link breaks, it is a content bug — report it so it can be swapped for the canonical source.'
    ].join('\n')
};
